### PR TITLE
Upgrade grpc-gateway to fix Mend reported vulnerabilities

### PR DESCRIPTION
**Pull request by shawnhankim**
This is to upgrade `grpc-gateway` to fix security vulnerabilities which are reported by Mend.
- [x] grpc-gateway: v1 -> v2 (github.com/grpc-ecosystem/grpc-gateway/v2)
- [x] upgrade github.com/gogo/googleapis to v1.4.1
- [x] mashaler.go: Add a param in the ContentType() based on upgrading grpc-gateway
- [x] fix unit test code
- [x] upgrade go version: `1.12 -> 1.21`

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
Hi, I don't think this will be possible as the v2 of the gateway uses the new Go generator toolchain while gogo protobuf does not support this generator toolchan.

**Comment by shawnhankim** [comment]
- Thanks @johanbrandhorst for the prompt feedback. 
- I am upgrading `grpc-gateway` to several projects based on the security tool's recommendation because it uses old version of `gopkg.in/resty` which is vulnerable.
- This `gogo/gateway` is one of dependencies that uses old version of `grpc-gateway` so I am trying upgrading this.
- I will see if I can either find other library rather than this or try alternative solutions using this repo.
- Feel free to let me know if you have any other recommendation in the meantime.

**Comment by johanbrandhorst** [comment]
I appreciate the effort, but as I said, this repo isn't really possible to upgrade to v2 of the gateway. I recommend removing the dependency on this repository and switching directly to the modern protobuf stack.

**Comment by shawnhankim** [comment]
Thanks @johanbrandhorst for your time and recommendation!

**Pull request closed without merging**
