### PR TITLE
Migrate to go modules

### PR DESCRIPTION
**Pull request by johanbrandhorst**

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
We'll probably have to release v2.0.0 with this, but that should be okay

**Comment by johanbrandhorst** [comment]
Ah, the major version increment recommendation only applies to v2+ packages: https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher. This'll just be v1.1.0 then.

**Comment by johanbrandhorst** [comment]
@jmarais I'm happy to merge this on my own but I will leave 24 hours from the creation of this PR in case you have any thoughts.

**Comment by awalterschulze** [comment]
Sorry I am unfamiliar with go modules. So I am probably not the best person
to review this.

**Pull request merged**
